function [spinImgs selIxs] = buildAndStoreDescriptor(pts, filePath, ...
    noOfSpinImgs, distance,  ...
	alfaBins, betaBins, alfaAxes, betaAxes)
%Tworzy deskryptor i zapisuje go do pliku o ile 
%plik jeszcze nie istnieje.

[spinImgs selIxs] = getDescriptor(pts, filePath, ...
    noOfSpinImgs, distance, ...
    alfaBins, betaBins, alfaAxes, betaAxes);
	
ioStoreModelDescriptor(filePath, spinImgs, selIxs);
