function [spinImgs selIxs] = buildAndStoreDescriptorSub(pts, mask, filePath, ...
    noOfSeedPoints, distance, ...
    alfaBins, betaBins, alfaAxes, betaAxes)
%Tworzy deskryptor i zapisuje go do pliku o ile 
%plik jeszcze nie istnieje.

[spinImgs selIxs] = getDescriptorSub(pts, mask, filePath, ...
    noOfSeedPoints, distance, ...
    alfaBins, betaBins, alfaAxes, betaAxes);
	
ioStoreModelDescriptor(filePath, spinImgs, selIxs);
