function report = testPreprocessing(inPath, outPath)

pts = ioLoad3dData(inPath);

tic;
[facePts faceCost faceMatchingCosts optimalMaxDistanceCoeff ...
    removedToSmall neigborhoodRadius] = ...
    modelPreprocessing(pts);
t = toc;

report = [inPath ' ' num2str(t) ' ' num2str(size(pts,1)) ...
    ' ' num2str(removedToSmall) ' ' num2str(size(facePts,1)) ' '...
    num2str(faceCost) ' '...
    num2str(neigborhoodRadius) ' ' num2str(optimalMaxDistanceCoeff) ' '...
    num2str(faceMatchingCosts') ];

ioStore3dRawData(outPath, facePts);
